default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  adapter: mysql2
  database: asv_dev
  user: root
  pool: 5
  timeout: 5000

test:
  adapter: mysql2
  database: asv_test
  user: root
  pool: 5
  timeout: 5000

production:
  <<: *default
  database: db/production.sqlite3
